sudo: false

language: ruby

rvm:
  - 2.2

install:
  - curl -L -o jupyter-scala https://raw.githubusercontent.com/alexarchambault/jupyter-scala/master/jupyter-scala
  - bash jupyter-scala
  - bundle install

script: bundle exec jekyll build
